### ISSUE TITLE
Investigate HDFS errors

### ISSUE THREAD

**Issue by dvenza** [DistributedSystemsGroup/zoe#18]
HDFS in Docker containers has some troubles with overlay networks. Doing a copyFromLocal from the namenode outputs these errors:

```
16/03/30 08:33:32 INFO hdfs.DFSClient: Exception in createBlockOutputStream
java.io.IOException: Bad connect ack with firstBadLink as 10.0.0.11:50010
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1460)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1361)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:588)
16/03/30 08:33:32 INFO hdfs.DFSClient: Abandoning BP-1699471697-10.0.0.2-1454672112057:blk_1073745823_4999
16/03/30 08:33:32 INFO hdfs.DFSClient: Excluding datanode 10.0.0.11:50010
16/03/30 08:34:42 INFO hdfs.DFSClient: Exception in createBlockOutputStream
java.io.IOException: Bad connect ack with firstBadLink as 10.0.0.10:50010
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1460)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1361)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:588)
16/03/30 08:34:42 INFO hdfs.DFSClient: Abandoning BP-1699471697-10.0.0.2-1454672112057:blk_1073745828_5004
16/03/30 08:34:42 INFO hdfs.DFSClient: Excluding datanode 10.0.0.10:50010
16/03/30 08:35:55 INFO hdfs.DFSClient: Exception in createBlockOutputStream
java.io.IOException: Bad connect ack with firstBadLink as 10.0.0.6:50010
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1460)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1361)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:588)
16/03/30 08:35:55 INFO hdfs.DFSClient: Abandoning BP-1699471697-10.0.0.2-1454672112057:blk_1073745835_5011
16/03/30 08:35:55 INFO hdfs.DFSClient: Excluding datanode 10.0.0.6:50010
```

The file gets copied eventually.

**Comment by dvenza** [comment]
The datanodes were using 100% of the memory available in the container (1GB). I increased the memory to 2GB, will monitor to see if the errors keep happening.

**Comment by dvenza** [comment]
See #28
